server.port=8081
# application.properties (ou application-dev.properties, etc.)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8088/realms/master
# Datasource is configured via environment variables in docker-compose
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=users

# Course service base URL
course.service.url=http://course-service:8087
